### ISSUE TITLE
有可能是数组越界异常

### ISSUE THREAD

**Issue by TGhoul** [ForLovelj/v9porn#3]
### 运行环境 ###

- [x] 手机型号：如：`16Plus`
- [x] 系统版本：如 `Android 8.1`
- [x] APP 版本：`1.1.9`

### 具体问题描述(如何操作，有何提示文字等): ###

显示解析错误，length=1，index=3

**Comment by TGhoul** [comment]
我想帮助修改，但是证书密码不知道怎么弄，可以指教一下吗

**Comment by yuccacl** [comment]
网站改版，AddToFavorite抓不到导致的问题，直接屏蔽了就可以了

**Comment by TGhoul** [comment]
@yuccacl 你知道证书问题怎么搞吗，不知道证书密码本地没办法构建好像

**Comment by ForLovelj** [comment]
已修复
