### ISSUE TITLE
老哥不能用了，数组越界

### ISSUE THREAD

**Issue by Misakimmmm** [ForLovelj/v9porn#5]
### 运行环境 ###

- [x] 手机型号：如：`Nexus 6`
- [x] 系统版本：如 `Android 5.0`
- [x] APP 版本：`1.x.x`

**Comment by ForLovelj** [comment]
已修复

**Comment by Misakimmmm** [comment]
> 已修复

老哥你那能用吗，我这点进去一直转圈圈啊
