### ISSUE TITLE
老哥还打算更新吗？

### ISSUE THREAD

**Issue by xiechangan123** [ForLovelj/v9porn#9]
原作者更新太慢了，91更新太快了，app没几天就失效了

**Comment by ForLovelj** [comment]
我可以用啊，回头我把现在我用的包更新上来

**Comment by xiechangan123** [comment]
用了几天，成功下载过一个视频，但是之后一下载就崩溃。不知道什么原因。。。关键好作品想下载下来，不然大佬一删除，gg

**Comment by ForLovelj** [comment]
> 用了几天，成功下载过一个视频，但是之后一下载就崩溃。不知道什么原因。。。关键好作品想下载下来，不然大佬一删除，gg

新视频我这边都能下，老视频播放和下载有问题，久了没用网站又改了老视频的解析和播放，回头有时间更新把日志加上。

**Comment by ForLovelj** [comment]
更新了下载还有问题联系我
